version: '3.8'

services:
  codex-web:
    image: wenfxl/wenfxl-codex-manager:v1.0
    container_name: wenfxl_codex_manager
    ports:
      - "8000:8000"
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./data:/app/data